apiVersion: k8s.elx.cloud/v1alpha2
kind: NodeGroup
metadata:
  name: nodegroup-sample
spec:
  nodeGroupNames: ["default"]
  labels:
    environment: production
  taints:
    - key: dedicated
      value: "special"
      effect: NoSchedule
  startupTaints:
    - key: node.istio.io/ambient-not-ready
      value: "true"
      effect: NoSchedule
